"""changed created_at type to DateTime

Revision ID: 764a8e5f5f5a
Revises: 6640f246318e
Create Date: 2023-09-25 14:48:34.009395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764a8e5f5f5a'
down_revision = '6640f246318e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
